-- Tạo database
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'task_manager_db')
BEGIN
    CREATE DATABASE task_manager_db;
END
GO

USE task_manager_db;
GO

-- Tạo schema
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'task_manager')
BEGIN
    EXEC('CREATE SCHEMA task_manager');
END
GO

-- Bảng Users
CREATE TABLE task_manager.Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Username NVARCHAR(50) NOT NULL UNIQUE,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);
GO

-- Bảng Projects
CREATE TABLE task_manager.Projects (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES task_manager.Users(Id) ON DELETE NO ACTION,
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX),
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);
GO

-- Bảng Tasks
CREATE TABLE task_manager.Tasks (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES task_manager.Users(Id) ON DELETE NO ACTION,
    ProjectId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES task_manager.Projects(Id) ON DELETE NO ACTION,
    Title NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX),
    Priority SMALLINT NOT NULL CHECK (Priority BETWEEN 1 AND 5),
    DueDate DATETIMEOFFSET,
    Status NVARCHAR(20) NOT NULL DEFAULT 'ToDo' CHECK (Status IN ('ToDo', 'InProgress', 'Done')),
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);
GO

-- Bảng Reminders
CREATE TABLE task_manager.Reminders (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TaskId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES task_manager.Tasks(Id) ON DELETE NO ACTION,
    ReminderTime DATETIMEOFFSET NOT NULL,
    Method NVARCHAR(20) NOT NULL CHECK (Method IN ('Email', 'Notification', 'SMS')),
    IsSent BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);
GO

-- Bảng AI_Suggestions
CREATE TABLE task_manager.AI_Suggestions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TaskId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES task_manager.Tasks(Id) ON DELETE NO ACTION,
    SuggestedStartTime DATETIMEOFFSET,
    Reason NVARCHAR(MAX),
    ConfidenceScore DECIMAL(5,2) CHECK (ConfidenceScore BETWEEN 0 AND 1),
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);
GO

-- Bảng Integrations
CREATE TABLE task_manager.Integrations (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES task_manager.Users(Id) ON DELETE NO ACTION,
    Type NVARCHAR(20) NOT NULL CHECK (Type IN ('GoogleCalendar', 'Email')),
    AccessToken NVARCHAR(MAX),
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);
GO